// <auto-generated />
using System;
using Armadar.ExchangerService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Armadar.ExchangerService.Migrations
{
    [DbContext(typeof(ExchangerContext))]
    [Migration("20190420210504_fixing column types")]
    partial class fixingcolumntypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Armadar.ExchangerService.Entities.Exchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateRate");

                    b.Property<string>("from")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("operation")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("to")
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Exchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
